import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.primary,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray200,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            18,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray60001,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            65,
          ),
          fontFamily: 'Playfair Display',
          fontWeight: FontWeight.w500,
        ),
        displayMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            48,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
        displaySmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: getFontSize(
            36,
          ),
          fontFamily: 'Playfair Display',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.primaryContainer,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Playfair Display',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Lato',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF5F6AFF),
    primaryContainer: Color(0XFF1E232C),
    secondary: Color(0XFF1E232C),
    secondaryContainer: Color(0XFF808080),
    tertiary: Color(0XFF1E232C),
    tertiaryContainer: Color(0XFF808080),

    // Background colors
    background: Color(0XFF1E232C),

    // Surface colors
    surface: Color(0XFF1E232C),
    surfaceTint: Color(0XFF181818),
    surfaceVariant: Color(0XFF808080),

    // Error colors
    error: Color(0XFF181818),
    errorContainer: Color(0XFF626260),
    onError: Color(0XFFA1A1A1),
    onErrorContainer: Color(0XFF181818),

    // On colors(text colors)
    onBackground: Color(0XFFC1C5FE),
    onInverseSurface: Color(0XFFA1A1A1),
    onPrimary: Color(0XFF181818),
    onPrimaryContainer: Color(0XFFC1C5FE),
    onSecondary: Color(0XFFC1C5FE),
    onSecondaryContainer: Color(0XFF181818),
    onTertiary: Color(0XFFC1C5FE),
    onTertiaryContainer: Color(0XFF181818),

    // Other colors
    outline: Color(0XFF181818),
    outlineVariant: Color(0XFF1E232C),
    scrim: Color(0XFF1E232C),
    shadow: Color(0XFF181818),

    // Inverse colors
    inversePrimary: Color(0XFF1E232C),
    inverseSurface: Color(0XFF181818),

    // Pending colors
    onSurface: Color(0XFFC1C5FE),
    onSurfaceVariant: Color(0XFF181818),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF00032D);
  Color get black90001 => Color(0XFF000000);

  // Blue
  Color get blue50 => Color(0XFFEAECFF);
  Color get blueA200 => Color(0XFF4091FF);

  // BlueGray
  Color get blueGray100 => Color(0XFFD0CBC9);
  Color get blueGray10001 => Color(0XFFD4CFCA);
  Color get blueGray10002 => Color(0XFFD4CFCB);
  Color get blueGray400 => Color(0XFF8A8A8A);
  Color get blueGray40001 => Color(0XFF8390A1);
  Color get blueGray40002 => Color(0XFF888888);

  // Gray
  Color get gray200 => Color(0XFFF0F0F0);
  Color get gray300 => Color(0XFFDFDBD9);
  Color get gray400 => Color(0XFFCBBCB1);
  Color get gray50 => Color(0XFFF9FAFF);
  Color get gray5001 => Color(0XFFFCFCFC);
  Color get gray5002 => Color(0XFFF7F8FA);
  Color get gray600 => Color(0XFF6A707C);
  Color get gray60001 => Color(0XFF7E7A77);
  Color get gray60002 => Color(0XFF887568);
  Color get gray900 => Color(0XFF222326);

  // Indigo
  Color get indigo50 => Color(0XFFE8ECF4);

  // Red
  Color get red400 => Color(0XFFEB5757);
  Color get red500 => Color(0XFFF14336);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
